version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: az_worldofgames_level4:latest
    container_name: wog_web_app
    ports:
      - "5001:5000"
    volumes:
      - type: bind
        source: ./scores.txt
        target: /app/scores.txt
    environment:
      - FLASK_ENV=development
    restart: on-failure
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-standalone-chrome
    ports:
      - "4444:4444"
    restart: on-failure
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge
